language: python
python:
    - '2.5'
    - '2.6'
    - '2.7'
    - 'pypy'
before_install:
    - 'sudo apt-get install libsdl1.2-dev libv4l-dev libjpeg8-dev'
    - 'git clone --depth 1 git://github.com/dlbeer/quirc.git /tmp/quirc'
    - 'make -C /tmp/quirc libquirc.so libquirc.a'
    - 'sudo make -C /tmp/quirc install'
script: LD_PRELOAD=/usr/local/lib/libquirc.so.1.0 python setup.py test