language: python

python:
    - '2.5'
    - '2.6'
    - '2.7'
    - 'pypy'

# Compile C library
before_install:
    - 'sudo apt-get install libsdl1.2-dev zlib-bin zlib1g-dev zlibc libpng-dev'
    - 'git clone --depth 1 git://github.com/dlbeer/quirc.git /tmp/quirc'
    - 'make -C /tmp/quirc libquirc.so libquirc.a'
    - 'sudo install -o root -g root -m 0644 /tmp/quirc/libquirc.a /usr/local/lib'
    - 'sudo install -o root -g root -m 0755 /tmp/quirc/libquirc.so /usr/local/lib/libquirc.so.1.0'
    - 'sudo ln -sf /usr/local/lib/libquirc.so.1.0 /usr/local/lib/libquirc.so.1'
    - 'sudo ln -sf /usr/local/lib/libquirc.so.1.0 /usr/local/lib/libquirc.so'

# Install test dependencies
install:
    - 'sudo pip install Pillow pep8 --use-mirrors'
    - 'if [[ $TRAVIS_PYTHON_VERSION == "2.5" ]]; then sudo pip install unittest2 --use-mirrors; fi'
    - 'if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then sudo pip install unittest2 --use-mirrors; fi'

before_script:
    - 'pep8 --ignore=E501,E225 quirc'

# Rock'n'roll!
script: LD_PRELOAD=/usr/local/lib/libquirc.so python setup.py test
